# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Как зовут')),
                ('has_money', models.BooleanField(default=False, verbose_name='С деньгами')),
                ('is_generous', models.BooleanField(default=False, verbose_name='Щедрый')),
            ],
        ),
    ]
