# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Survey',
            new_name='SurveyRes',
        ),
    ]
