# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180314_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyres',
            name='is_generous',
            field=models.NullBooleanField(verbose_name='Щедрый'),
        ),
    ]
