# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180314_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyres',
            options={'verbose_name': 'Результат опроса', 'verbose_name_plural': 'Результаты опросов'},
        ),
        migrations.AddField(
            model_name='surveyres',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
